# Configuration of where to symlink the various dotfiles.
# Paths are relative to the dotfiles folder.

# .bashrc files
- from: ~/.bashrc
  to: bashrc
- from: ~/.bashrc.d
  to: bashrc.d

# git files
- from: ~/.gitconfig
  to: gitconfig
- from: ~/.gitignore
  to: gitignore

# python
- from: ~/.pythonrc.py
  to: pythonrc.py

# misc
- from: ~/.vimperatorrc
  to: vimperatorrc
